INSERT INTO tdwproject.availability (id, user_fk, partner_fk, sport_fk, date, time, busy) VALUES (1, 1, 1, 1, '2018-01-13', '11:00:00', 0);
INSERT INTO tdwproject.availability (id, user_fk, partner_fk, sport_fk, date, time, busy) VALUES (5, 1, 1, 1, '2018-01-17', null, 1);
INSERT INTO tdwproject.availability (id, user_fk, partner_fk, sport_fk, date, time, busy) VALUES (6, 1, 1, 1, '2018-01-31', null, 0);
INSERT INTO tdwproject.availability (id, user_fk, partner_fk, sport_fk, date, time, busy) VALUES (7, 2, 1, 1, '2018-01-31', null, 0);
INSERT INTO tdwproject.booking (id, date, time, user_fk, field_fk, approved, valid) VALUES (1, '2018-01-18', '11:00:00', 1, 1, 1, 0);
INSERT INTO tdwproject.booking (id, date, time, user_fk, field_fk, approved, valid) VALUES (2, '2018-01-15', '09:00:00', 1, 2, 1, 1);
INSERT INTO tdwproject.booking (id, date, time, user_fk, field_fk, approved, valid) VALUES (6, '2018-02-16', '12:00:00', null, 2, 0, 1);
INSERT INTO tdwproject.booking (id, date, time, user_fk, field_fk, approved, valid) VALUES (7, '2018-02-23', '12:00:00', null, 2, 0, 1);
INSERT INTO tdwproject.booking (id, date, time, user_fk, field_fk, approved, valid) VALUES (8, '2018-02-15', '12:00:00', null, 2, 0, 1);
INSERT INTO tdwproject.booking (id, date, time, user_fk, field_fk, approved, valid) VALUES (9, '2018-02-08', '11:00:00', null, 2, 0, 1);
INSERT INTO tdwproject.booking (id, date, time, user_fk, field_fk, approved, valid) VALUES (10, '2018-02-15', '11:00:00', null, 2, 0, 1);
INSERT INTO tdwproject.booking (id, date, time, user_fk, field_fk, approved, valid) VALUES (11, '2018-02-15', '11:00:00', null, 2, 0, 1);
INSERT INTO tdwproject.booking (id, date, time, user_fk, field_fk, approved, valid) VALUES (12, '2018-02-15', '11:00:00', null, 2, 0, 1);
INSERT INTO tdwproject.booking (id, date, time, user_fk, field_fk, approved, valid) VALUES (13, '2018-02-15', '11:00:00', null, 2, 0, 1);
INSERT INTO tdwproject.booking (id, date, time, user_fk, field_fk, approved, valid) VALUES (14, '2018-02-15', '11:00:00', null, 2, 0, 1);
INSERT INTO tdwproject.booking (id, date, time, user_fk, field_fk, approved, valid) VALUES (15, '2018-02-23', '14:00:00', null, 2, 0, 1);
INSERT INTO tdwproject.booking (id, date, time, user_fk, field_fk, approved, valid) VALUES (16, '2018-02-21', '13:00:00', null, 2, 0, 1);
INSERT INTO tdwproject.booking (id, date, time, user_fk, field_fk, approved, valid) VALUES (17, '2018-02-08', '12:00:00', null, 2, 0, 1);
INSERT INTO tdwproject.field (id, partner_fk, sport_fk, outdoor, province_fk, type, warmed, number) VALUES (1, 1, 1, 1, 'RM', 'Erba sintetica', 0, 2);
INSERT INTO tdwproject.field (id, partner_fk, sport_fk, outdoor, province_fk, type, warmed, number) VALUES (2, 1, 1, 1, 'RM', 'Erba sintetica', 0, 1);
INSERT INTO tdwproject.invitation (id, from_user_fk, to_user_fk, date, status, availability_fk) VALUES (1, 1, 2, '2018-01-30 12:12:16', 2, 1);
INSERT INTO tdwproject.invitation (id, from_user_fk, to_user_fk, date, status, availability_fk) VALUES (2, 2, 1, '2018-01-30 15:52:05', 1, 5);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (182, 5, 14, 1, '2018-02-08', '12:00:00', 2, 0);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (183, 6, 9, 1, null, null, null, 0);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (184, 10, 13, 1, null, null, null, 0);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (185, 11, 12, 1, null, null, null, 0);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (186, 16, 15, 1, null, null, null, 0);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (187, 9, 5, 1, null, null, null, 1);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (188, 12, 16, 1, null, null, null, 1);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (189, 13, 11, 1, null, null, null, 1);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (190, 14, 10, 1, null, null, null, 1);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (191, 15, 6, 1, null, null, null, 1);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (192, 5, 15, 1, null, null, null, 2);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (193, 6, 12, 1, null, null, null, 2);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (194, 10, 9, 1, null, null, null, 2);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (195, 14, 13, 1, null, null, null, 2);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (196, 16, 11, 1, null, null, null, 2);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (197, 9, 14, 1, null, null, null, 3);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (198, 11, 6, 1, null, null, null, 3);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (199, 12, 5, 1, null, null, null, 3);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (200, 13, 16, 1, null, null, null, 3);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (201, 15, 10, 1, null, null, null, 3);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (202, 5, 11, 1, null, null, null, 4);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (203, 6, 16, 1, null, null, null, 4);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (204, 9, 13, 1, null, null, null, 4);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (205, 10, 12, 1, null, null, null, 4);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (206, 14, 15, 1, null, null, null, 4);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (207, 11, 10, 1, null, null, null, 5);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (208, 12, 14, 1, null, null, null, 5);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (209, 13, 6, 1, null, null, null, 5);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (210, 15, 9, 1, null, null, null, 5);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (211, 16, 5, 1, null, null, null, 5);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (212, 5, 6, 1, null, null, null, 6);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (213, 9, 12, 1, null, null, null, 6);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (214, 10, 16, 1, null, null, null, 6);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (215, 14, 11, 1, null, null, null, 6);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (216, 15, 13, 1, null, null, null, 6);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (217, 5, 13, 1, null, null, null, 7);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (218, 6, 10, 1, null, null, null, 7);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (219, 11, 9, 1, null, null, null, 7);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (220, 12, 15, 1, null, null, null, 7);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (221, 16, 14, 1, null, null, null, 7);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (222, 9, 16, 1, null, null, null, 8);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (223, 10, 5, 1, null, null, null, 8);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (224, 13, 12, 1, null, null, null, 8);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (225, 14, 6, 1, null, null, null, 8);
INSERT INTO tdwproject.`match` (id, first_team_fk, second_team_fk, tournament_fk, date, time, field_fk, day) VALUES (226, 15, 11, 1, null, null, null, 8);
INSERT INTO tdwproject.partner (id, name, description, region, area, address, email, telnumber) VALUES (1, 'Centro sportivo porca puttana', 'BBBB', 'CCC', 'AA', 'gvfb', 'fgvdfbgn', 'vfbfgb45rg');
INSERT INTO tdwproject.province (sign, name) VALUES ('AG', 'Agrigento');
INSERT INTO tdwproject.province (sign, name) VALUES ('AL', 'Alessandria');
INSERT INTO tdwproject.province (sign, name) VALUES ('AN', 'Ancona');
INSERT INTO tdwproject.province (sign, name) VALUES ('AO', 'Aosta');
INSERT INTO tdwproject.province (sign, name) VALUES ('AP', 'Ascoli Piceno');
INSERT INTO tdwproject.province (sign, name) VALUES ('AQ', 'L''Aquila');
INSERT INTO tdwproject.province (sign, name) VALUES ('AR', 'Arezzo');
INSERT INTO tdwproject.province (sign, name) VALUES ('AT', 'Asti');
INSERT INTO tdwproject.province (sign, name) VALUES ('AV', 'Avellino');
INSERT INTO tdwproject.province (sign, name) VALUES ('BA', 'Bari');
INSERT INTO tdwproject.province (sign, name) VALUES ('BG', 'Bergamo');
INSERT INTO tdwproject.province (sign, name) VALUES ('BI', 'Biella');
INSERT INTO tdwproject.province (sign, name) VALUES ('BL', 'Belluno');
INSERT INTO tdwproject.province (sign, name) VALUES ('BN', 'Benevento');
INSERT INTO tdwproject.province (sign, name) VALUES ('BO', 'Bologna');
INSERT INTO tdwproject.province (sign, name) VALUES ('BR', 'Brindisi');
INSERT INTO tdwproject.province (sign, name) VALUES ('BS', 'Brescia');
INSERT INTO tdwproject.province (sign, name) VALUES ('BT', 'Barletta-Andria-Trani');
INSERT INTO tdwproject.province (sign, name) VALUES ('BZ', 'Bolzano');
INSERT INTO tdwproject.province (sign, name) VALUES ('CA', 'Cagliari');
INSERT INTO tdwproject.province (sign, name) VALUES ('CB', 'Campobasso');
INSERT INTO tdwproject.province (sign, name) VALUES ('CE', 'Caserta');
INSERT INTO tdwproject.province (sign, name) VALUES ('CH', 'Chieti');
INSERT INTO tdwproject.province (sign, name) VALUES ('CI', 'Carbonia-Iglesias');
INSERT INTO tdwproject.province (sign, name) VALUES ('CL', 'Caltanissetta');
INSERT INTO tdwproject.province (sign, name) VALUES ('CN', 'Cuneo');
INSERT INTO tdwproject.province (sign, name) VALUES ('CO', 'Como');
INSERT INTO tdwproject.province (sign, name) VALUES ('CR', 'Cremona');
INSERT INTO tdwproject.province (sign, name) VALUES ('CS', 'Cosenza');
INSERT INTO tdwproject.province (sign, name) VALUES ('CT', 'Catania');
INSERT INTO tdwproject.province (sign, name) VALUES ('CZ', 'Catanzaro');
INSERT INTO tdwproject.province (sign, name) VALUES ('EN', 'Enna');
INSERT INTO tdwproject.province (sign, name) VALUES ('FC', 'ForlÃ¬-Cesena');
INSERT INTO tdwproject.province (sign, name) VALUES ('FE', 'Ferrara');
INSERT INTO tdwproject.province (sign, name) VALUES ('FG', 'Foggia');
INSERT INTO tdwproject.province (sign, name) VALUES ('FI', 'Firenze');
INSERT INTO tdwproject.province (sign, name) VALUES ('FM', 'Fermo');
INSERT INTO tdwproject.province (sign, name) VALUES ('FR', 'Frosinone');
INSERT INTO tdwproject.province (sign, name) VALUES ('GE', 'Genova');
INSERT INTO tdwproject.province (sign, name) VALUES ('GO', 'Gorizia');
INSERT INTO tdwproject.province (sign, name) VALUES ('GR', 'Grosseto');
INSERT INTO tdwproject.province (sign, name) VALUES ('IM', 'Imperia');
INSERT INTO tdwproject.province (sign, name) VALUES ('IS', 'Isernia');
INSERT INTO tdwproject.province (sign, name) VALUES ('KR', 'Crotone');
INSERT INTO tdwproject.province (sign, name) VALUES ('LC', 'Lecco');
INSERT INTO tdwproject.province (sign, name) VALUES ('LE', 'Lecce');
INSERT INTO tdwproject.province (sign, name) VALUES ('LI', 'Livorno');
INSERT INTO tdwproject.province (sign, name) VALUES ('LO', 'Lodi');
INSERT INTO tdwproject.province (sign, name) VALUES ('LT', 'Latina');
INSERT INTO tdwproject.province (sign, name) VALUES ('LU', 'Lucca');
INSERT INTO tdwproject.province (sign, name) VALUES ('MB', 'Monza e della Brianza');
INSERT INTO tdwproject.province (sign, name) VALUES ('MC', 'Macerata');
INSERT INTO tdwproject.province (sign, name) VALUES ('ME', 'Messina');
INSERT INTO tdwproject.province (sign, name) VALUES ('MI', 'Milano');
INSERT INTO tdwproject.province (sign, name) VALUES ('MN', 'Mantova');
INSERT INTO tdwproject.province (sign, name) VALUES ('MO', 'Modena');
INSERT INTO tdwproject.province (sign, name) VALUES ('MS', 'Massa-Carrara');
INSERT INTO tdwproject.province (sign, name) VALUES ('MT', 'Matera');
INSERT INTO tdwproject.province (sign, name) VALUES ('NA', 'Napoli');
INSERT INTO tdwproject.province (sign, name) VALUES ('NO', 'Novara');
INSERT INTO tdwproject.province (sign, name) VALUES ('NU', 'Nuoro');
INSERT INTO tdwproject.province (sign, name) VALUES ('OG', 'Ogliastra');
INSERT INTO tdwproject.province (sign, name) VALUES ('OR', 'Oristano');
INSERT INTO tdwproject.province (sign, name) VALUES ('OT', 'Olbia-Tempio');
INSERT INTO tdwproject.province (sign, name) VALUES ('PA', 'Palermo');
INSERT INTO tdwproject.province (sign, name) VALUES ('PC', 'Piacenza');
INSERT INTO tdwproject.province (sign, name) VALUES ('PD', 'Padova');
INSERT INTO tdwproject.province (sign, name) VALUES ('PE', 'Pescara');
INSERT INTO tdwproject.province (sign, name) VALUES ('PG', 'Perugia');
INSERT INTO tdwproject.province (sign, name) VALUES ('PI', 'Pisa');
INSERT INTO tdwproject.province (sign, name) VALUES ('PN', 'Pordenone');
INSERT INTO tdwproject.province (sign, name) VALUES ('PO', 'Prato');
INSERT INTO tdwproject.province (sign, name) VALUES ('PR', 'Parma');
INSERT INTO tdwproject.province (sign, name) VALUES ('PT', 'Pistoia');
INSERT INTO tdwproject.province (sign, name) VALUES ('PU', 'Pesaro e Urbino');
INSERT INTO tdwproject.province (sign, name) VALUES ('PV', 'Pavia');
INSERT INTO tdwproject.province (sign, name) VALUES ('PZ', 'Potenza');
INSERT INTO tdwproject.province (sign, name) VALUES ('RA', 'Ravenna');
INSERT INTO tdwproject.province (sign, name) VALUES ('RC', 'Reggio Calabria');
INSERT INTO tdwproject.province (sign, name) VALUES ('RE', 'Reggio Emilia');
INSERT INTO tdwproject.province (sign, name) VALUES ('RG', 'Ragusa');
INSERT INTO tdwproject.province (sign, name) VALUES ('RI', 'Rieti');
INSERT INTO tdwproject.province (sign, name) VALUES ('RM', 'Roma');
INSERT INTO tdwproject.province (sign, name) VALUES ('RN', 'Rimini');
INSERT INTO tdwproject.province (sign, name) VALUES ('RO', 'Rovigo');
INSERT INTO tdwproject.province (sign, name) VALUES ('SA', 'Salerno');
INSERT INTO tdwproject.province (sign, name) VALUES ('SI', 'Siena');
INSERT INTO tdwproject.province (sign, name) VALUES ('SO', 'Sondrio');
INSERT INTO tdwproject.province (sign, name) VALUES ('SP', 'La Spezia');
INSERT INTO tdwproject.province (sign, name) VALUES ('SR', 'Siracusa');
INSERT INTO tdwproject.province (sign, name) VALUES ('SS', 'Sassari');
INSERT INTO tdwproject.province (sign, name) VALUES ('SV', 'Savona');
INSERT INTO tdwproject.province (sign, name) VALUES ('TA', 'Taranto');
INSERT INTO tdwproject.province (sign, name) VALUES ('TE', 'Teramo');
INSERT INTO tdwproject.province (sign, name) VALUES ('TN', 'Trento');
INSERT INTO tdwproject.province (sign, name) VALUES ('TO', 'Torino');
INSERT INTO tdwproject.province (sign, name) VALUES ('TP', 'Trapani');
INSERT INTO tdwproject.province (sign, name) VALUES ('TR', 'Terni');
INSERT INTO tdwproject.province (sign, name) VALUES ('TS', 'Trieste');
INSERT INTO tdwproject.province (sign, name) VALUES ('TV', 'Treviso');
INSERT INTO tdwproject.province (sign, name) VALUES ('UD', 'Udine');
INSERT INTO tdwproject.province (sign, name) VALUES ('VA', 'Varese');
INSERT INTO tdwproject.province (sign, name) VALUES ('VB', 'Verbano-Cusio-Ossola');
INSERT INTO tdwproject.province (sign, name) VALUES ('VC', 'Vercelli');
INSERT INTO tdwproject.province (sign, name) VALUES ('VE', 'Venezia');
INSERT INTO tdwproject.province (sign, name) VALUES ('VI', 'Vicenza');
INSERT INTO tdwproject.province (sign, name) VALUES ('VR', 'Verona');
INSERT INTO tdwproject.province (sign, name) VALUES ('VS', 'Medio Campidano');
INSERT INTO tdwproject.province (sign, name) VALUES ('VT', 'Viterbo');
INSERT INTO tdwproject.province (sign, name) VALUES ('VV', 'Vibo Valentia');
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (1, 1, 182, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (2, 1, 183, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (3, 1, 184, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (4, 1, 185, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (5, 1, 186, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (6, 1, 187, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (7, 1, 188, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (8, 1, 189, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (9, 1, 190, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (10, 1, 191, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (11, 1, 192, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (12, 1, 193, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (13, 1, 194, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (14, 1, 195, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (15, 1, 196, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (16, 1, 197, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (17, 1, 198, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (18, 1, 199, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (19, 1, 200, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (20, 1, 201, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (21, 1, 202, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (22, 1, 203, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (23, 1, 204, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (24, 1, 205, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (25, 1, 206, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (26, 1, 207, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (27, 1, 208, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (28, 1, 209, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (29, 1, 210, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (30, 1, 211, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (31, 1, 212, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (32, 1, 213, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (33, 1, 214, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (34, 1, 215, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (35, 1, 216, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (36, 1, 217, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (37, 1, 218, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (38, 1, 219, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (39, 1, 220, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (40, 1, 221, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (41, 1, 222, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (42, 1, 223, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (43, 1, 224, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (44, 1, 225, 0);
INSERT INTO tdwproject.ranking (id, tournament_fk, team_fk, point) VALUES (45, 1, 226, 0);
INSERT INTO tdwproject.review (id, user_fk, text, stars, approved) VALUES (1, 1, 'qqqqqqqqq', 5, 1);
INSERT INTO tdwproject.sport (id, name, number_players) VALUES (1, 'Calcetto', 5);
INSERT INTO tdwproject.sport (id, name, number_players) VALUES (2, 'Calcio', 11);
INSERT INTO tdwproject.team (id, name, number, user_fk, players, tournament_fk) VALUES (5, 'Squadra1', 35346, 1, 'Tizio TizioTizio TizioTizio TizioTizio Tizio', 1);
INSERT INTO tdwproject.team (id, name, number, user_fk, players, tournament_fk) VALUES (6, 'Squadra2', 35346, 1, 'Tizio TizioTizio TizioTizio TizioTizio Tizio', 1);
INSERT INTO tdwproject.team (id, name, number, user_fk, players, tournament_fk) VALUES (9, 'Squadra3', 35346, 1, 'Tizio TizioTizio TizioTizio TizioTizio Tizio', 1);
INSERT INTO tdwproject.team (id, name, number, user_fk, players, tournament_fk) VALUES (10, 'Squadra4', 35346, 1, 'Tizio TizioTizio TizioTizio TizioTizio Tizio', 1);
INSERT INTO tdwproject.team (id, name, number, user_fk, players, tournament_fk) VALUES (11, 'Squadra5', 35346, 1, 'Tizio TizioTizio TizioTizio TizioTizio Tizio', 1);
INSERT INTO tdwproject.team (id, name, number, user_fk, players, tournament_fk) VALUES (12, 'Squadra6', 35346, 1, 'Tizio TizioTizio TizioTizio TizioTizio Tizio', 1);
INSERT INTO tdwproject.team (id, name, number, user_fk, players, tournament_fk) VALUES (13, 'Squadra7', 35346, 1, 'Tizio TizioTizio TizioTizio TizioTizio Tizio', 1);
INSERT INTO tdwproject.team (id, name, number, user_fk, players, tournament_fk) VALUES (14, 'Squadra8', 35346, 1, 'Tizio TizioTizio TizioTizio TizioTizio Tizio', 1);
INSERT INTO tdwproject.team (id, name, number, user_fk, players, tournament_fk) VALUES (15, 'Squadra9', 35346, 1, 'Tizio TizioTizio TizioTizio TizioTizio Tizio', 1);
INSERT INTO tdwproject.team (id, name, number, user_fk, players, tournament_fk) VALUES (16, 'Squadra10', 35346, 1, 'Tizio TizioTizio TizioTizio TizioTizio Tizio', 1);
INSERT INTO tdwproject.tournament (id, name, partner_fk, startDate, endSubscription, teamNumber, teamLeft, sport_fk, scheduled) VALUES (1, 'Torneo1', 1, '2018-05-23', '2018-04-11', 12, 0, 1, 1);
INSERT INTO tdwproject.tournament (id, name, partner_fk, startDate, endSubscription, teamNumber, teamLeft, sport_fk, scheduled) VALUES (2, 'Torneo2', 1, '2018-05-23', '2018-04-11', 12, 1, 1, 1);
INSERT INTO tdwproject.user (firstName, lastName, id, email, password, telnumber, birthdate, created_at, active, tokenCode, gender, admin) VALUES ('Tizio', 'Caio', 1, 'a@gmail.com', 'test2', '3444444444', '2018-01-13', '2018-01-26', 1, '', 'M', 1);
INSERT INTO tdwproject.user (firstName, lastName, id, email, password, telnumber, birthdate, created_at, active, tokenCode, gender, admin) VALUES ('Luigi', 'Rossi', 2, 'abcd@gmail.com', 'test2', '8963456348546', '2018-01-18', '2018-01-26', 1, '', 'M', 0);
